### ISSUE TITLE
Date typo for fjh_hons_thesis?

### ISSUE THREAD

**Issue by dram** [Mercury-Language/www#11]
According to the content of Fergus Henderson's thesis "Strong modes can change the world!", it is published in "November 1993" instead of "November 1992", may be a typo?

Following two lines are affected:

1. [papers.inc#L856](https://github.com/Mercury-Language/www/blob/19ce775ef2a4ebe78385cbad8cd0e2054040df82/documentation/include/papers.inc#L856)
2. [papers.inc#L3883](https://github.com/Mercury-Language/www/blob/19ce775ef2a4ebe78385cbad8cd0e2054040df82/documentation/include/papers.inc#L3883)

**Comment by zsomogyi** [comment]
Fixed.
